language: clojure
script:
- lein sass4clj once
- lein cljsbuild once prod prod-site
- lein minify-assets
- lein uberjar
sudo: false
jdk:
- oraclejdk8
python:
  - "2.7"
branches:
  only:
  - staging
  - master
cache:
  directories:
  - "$HOME/.m2"
addons:
  ssh_known_hosts:
  - 138.68.237.182
  - 136.243.19.202
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_5edcd9343923_key -iv $encrypted_5edcd9343923_iv -in .travis/id_rsa.enc -out id_rsa -d
- chmod 400 id_rsa
- mv id_rsa ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git submodule update --remote
install:
  - sudo pip install requests --upgrade
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export APP="pg-prod"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="pg-stg"; fi
- .travis/skype.py $skype_id $skype_key $skype_chat_id $TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_BUILD_ID $TRAVIS_BUILD_NUMBER 1
- echo "Deploying to $SERVER"
- mv .travis/id_rsa.pub ~/.ssh/id_rsa.pub
- chmod 400 ~/.ssh/id_rsa
- chmod 400 ~/.ssh/id_rsa.pub
- ssh-add ~/.ssh/id_rsa
- scp target/pg-standalone.jar root@138.68.237.182:/apps/$APP/pg-standalone.jar
- ssh root@138.68.237.182 "supervisorctl restart $APP"
after_failure:
- .travis/skype.py $skype_id $skype_key $skype_chat_id $TRAVIS_REPO_SLUG $TRAVIS_BRANCH $TRAVIS_BUILD_ID $TRAVIS_BUILD_NUMBER 0
notifications:
  slack:
    secure: LGrosP+UjObWZGdvS3+HKWu9OO65ns8ILRgUPRbHHvIvkf/cIFiO/srQijqzmghauDgJp8GUjPYemH+6poTyS4X+vXqbN35wZ3fwNPX0Qoyv9P86DySky/XhUjCDQ9dhMut7MzK/uTwzVJh6euwHKzxMsfSpKjKj6OqN55uqn8NQlvuF31TaglEb+UarybwdOgG57EmxdJOBJZNVFvLk26PVEnQ9Eclz377kgNi7ZwHM1byJBeowiAwpunVqPvlze95KYyvx/+l7E9MjKJB0Ytg4mJiRzcIdK7bNBS3QNGmBPCWj5PVyF72Dy0+X8wt8nR+VLE4ACG9JWBLXMx2vmGj/zcJ6XUBjNKLZPl3P0sYcWA/pHJQTffETnJf+Knr5jaYwquSP85EvNMKrqpqgYEihw8MNIe7vC1Pj7n1UK8MsaHlxB1fNhvrKxjQjAa4u/aXeaCcFULSZ1Zs0qTme12O7k+4YXP/75iywh9S4KQDxq1vgKaVLi1ZIOecAPzrx50aY0A385gc/EFWZ2Oo6742V+1ICkful4TP1MOb77SQFWEfOGjd3k0GVnxAXBmHq4M/ps4HDvy5C6zlCvhQQV76m39R+oSUP/YrXU97nGCgYLAF72yBiqvSxT8Qw5W+6xzYQdmRpRz4h1qQVPrwX9US0QjIsBBAGtZsn514pB7M=
