language: clojure
script:
- lein sass4clj once
- lein cljsbuild once prod prod-site prod-admin
- lein minify-assets
- lein uberjar
sudo: false
jdk:
- oraclejdk8
python:
- '2.7'
branches:
  only:
  - staging
  - master
cache:
  directories:
  - "$HOME/.m2"
addons:
  ssh_known_hosts:
  - 138.68.237.182
  - 136.243.19.202
git:
  submodules: false
before_install:
- openssl aes-256-cbc -K $encrypted_500e779cfa6c_key -iv $encrypted_500e779cfa6c_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 400 ~/.ssh/id_rsa
- echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- git submodule update --init --recursive
- git submodule foreach "(git checkout master; git pull)"
install:
- sudo pip install "requests<2.28.0" --upgrade
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export APP="pg-prod"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="pg-stg"; fi
- echo "Deploying to $SERVER"
- mv .travis/id_rsa.pub ~/.ssh/id_rsa.pub
- chmod 400 ~/.ssh/id_rsa.pub
- ssh-add ~/.ssh/id_rsa
- scp target/pg-standalone.jar root@138.68.237.182:/apps/$APP/pg-standalone.jar
- ssh root@138.68.237.182 "supervisorctl restart $APP"
