language: clojure
lein: lein2
script:
- lein2 cljsbuild once prod prod-site
- lein2 uberjar
sudo: false
jdk:
- oraclejdk8
branches:
  only:
  - staging
  - master
cache:
  directories:
  - "$HOME/.m2"
addons:
  ssh_known_hosts:
  - 104.236.250.75
  - 136.243.19.202
git:
  submodules: false
before_install:
- sed -i 's/git@github.com:/https:\/\/$user:$password@github.com\//' .gitmodules
- git submodule update --init --recursive
- openssl aes-256-cbc -K $encrypted_5edcd9343923_key -iv $encrypted_5edcd9343923_iv -in id_rsa_irkutsk_anychart.enc -out id_rsa -d
- mv id_rsa .travis/id_rsa
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then export APP="pg-prod"; fi
- if [ "$TRAVIS_BRANCH" == "staging" ]; then export APP="pg-stg"; fi
- echo "Deploying to $SERVER"
- chmod 600 .travis/id_rsa
- chmod 600 .travis/id_rsa.pub
- ssh-add .travis/id_rsa
- scp -i .travis/id_rsa target/pg-standalone.jar root@104.236.250.75:/apps/$APP/pg-standalone.jar
# - scp -i .travis/id_rsa target/pg-standalone.jar root@136.243.19.202:/apps/$APP/pg-standalone.jar
- ssh root@104.236.250.75 "supervisorctl restart $APP"
# - ssh root@136.243.19.202 "supervisorctl restart $APP"
notifications:
  slack: anychart-team:sJRPhNn8Ur8yVdhvhgp6EbDM
